lib/Mojolicious/Plugin/OpenAPI.pm
t/not_implemented_hook.t

specifically this will allow you to return whatever you like in the
case of an endpoint not being implemented, for example mocking of
response data. add a test case to cover this addition

add a 501 helper to allow override of default response

---

lib/Mojolicious/Plugin/OpenAPI.pm
t/not_implemented_hook.t

don't assume that the return struct is a HASH and instead expect a
list of two items to be returned from the called method (one of the
NOT_FOUND, EXCEPTION, NOT_IMPLEMENTED methods or the overridden
openapi.not_implemented helper). we can then pass on the returned
data structure without any risk of stomping on the status key if
that should already exist and we can now support more than HASHes
in the data returned from the openapi.not_implemented helper
tweak test to check for above change

tweak setting of status code in before_render hook

---

lib/Mojolicious/Plugin/OpenAPI.pm
lib/Mojolicious/Plugin/OpenAPI/Guides/Security.pod
t/security-disabled.t
t/security.t

I have no idea if this should be merged, so I thought you could vote/decide.
What do you think?
@kivilahtio
@chandwki
Sidenote to @chandwki: You can now look up the spec in `under()` 12baad9899f3870025e67d225fdc0ab8cd1ed3a4
Sidenote to @leejo: Would it be cool to make a helper/extension that would do OAuth2 using this logic?

Add support for "securityDefinitions"

---

lib/Mojolicious/Plugin/OpenAPI.pm
lib/Mojolicious/Plugin/OpenAPI/Guides/Security.pod
t/security.t

Given the new security architecture, the injected OPTIONS routes (useful
for documentation and (when clever) CORS) were no longer accessible.
This patch explicitly exempts these generated OPTIONS handlers. Perhaps
in the future if CORS handling is added this could be addressed more
robustly there.

improve handling of OPTIONS routes wrt security

---

Makefile.PL

This module is my [CPAN PR Challenge](http://cpan-prc.org/) assignment for December.
Starting gently, here is a minor addition to specify the minimum perl version. The use of defined-or (//) in lib/Mojolicious/Plugin/OpenAPI.pm sets this at 5.10.

Specify minimum perl version (5.10)

---

t/yaml.t

The JSON::Validator seems to require at least version 0.67 of YAML::XS
to work. If an older version is installed the the test fails. I've
changed the pre-condition to check for a specific version of YAML::XS,
and if it's not installed the test is skipped, just as if the modules
wasn't installed at all.
This should most/all of the CPAN Testers failures.
This is part of the CPAN Pull Request Challenge, where I got
Mojolicious::Plugin::OpenAPI as my February assignment.

Add version check of yaml module when testing

---

lib/Mojolicious/Plugin/OpenAPI.pm
t/autorender.t

By default, Mojolicious will first try to find
`not_found.$mode.$format.*` before trying `not_found.$format.*`.
Somehow, the plugin was preventing that, but adding back one of the
checks from v1.30 fixes it.
This fixes one of the problems that 2.00 causes in Yancy. See https://github.com/preaction/Yancy/issues/18 and http://www.cpantesters.org/cpan/report/0f7cb956-c4c9-11e8-8f89-a365089b717b This change fixes the `t/standalone.t` test failure.

fix default error template lookup by mode

---

lib/Mojolicious/Plugin/OpenAPI.pm
lib/Mojolicious/Plugin/OpenAPI/Cors.pm
lib/Mojolicious/Plugin/OpenAPI/Security.pm

Detected automatically by the lintian tool whilst packaging this distribution for Debian

Fix spelling errors in documentation

---

lib/Mojolicious/Plugin/OpenAPI.pm

Rename the embedded template, so "GET /api" and "GET /api.json" return the same output.
See #117 for background info.

I want a less confusing response on GET "/api" from the example in the synopsis

---

Changes
cpanfile
lib/Mojolicious/Plugin/OpenAPI/SpecRenderer.pm
t/spec.t

I think this PR will fix #119.
> Get rid of x-bundled in spec output
Note that this change require JSON-Validator 3.08, which is not yet released. See https://github.com/mojolicious/json-validator/pull/154 for more details.

Need to bundle all responses from SpecRenderer to make OPTIONS render in a more human friendly way #119

---

lib/Mojolicious/Plugin/OpenAPI.pm
lib/Mojolicious/Plugin/OpenAPI/Security.pm
t/register.t
t/v2-security.t
t/v3-security.t

This PR 
1. Fixes bug with default_response_codes - Response object format changed between 2.0 and 3.0, so we need to add different type of response objects for 3.0 routes. I changed logic and used v3 default response feature. Maybe you'll find it not an appropriate solution, but it's easy to use my code to implement same logic both for 3.0 and 2.0 routes.
2. Adds support for 3.0 to Security Plugin.

Add support for /components/securitySchemes from OpenAPI 3.0 and add default response types

---

.travis.yml
t/renderer.t

Current test relies on the exception stringifying to `->message`. Which has changed with the deprecation of `->verbose`.
* #132

Fix failing renderer.t test

---

.travis.yml

Add 5.28 and keep [![Build Status](https://travis-ci.com/kiwiroy/mojolicious-plugin-openapi.svg?branch=trusty-only)](https://travis-ci.com/kiwiroy/mojolicious-plugin-openapi) to reduce contributor friction.

Use Trusty for perl <5.22

---

.perltidyrc

Now it's possible for the user to run perltidy manually.
Because perltidy is mandatory for getting patches into this repository

turn off -st option, to allow for "perltidy -b $filename"

---

lib/Mojolicious/Plugin/OpenAPI.pm

This PR resolves the failing test in openapi-client.
The code in the [openapi-client test](https://github.com/jhthorsen/openapi-client/blob/5b53b799a53712ecea77325aea144c19432550d4/t/command-local-with-ref.t#L15-L16) leads me to believe that the intent of an empty array for `default_response_codes` in the config is to not alter the definitions of the schema. In this case the function will return early.
**edit** with some [changes](https://github.com/kiwiroy/openapi-client/commit/02044d5b5c446eec5cbfa8dfbc27b98c1c5c0a37) to dependency installation the openapi-client status is now [![Build Status](https://travis-ci.com/kiwiroy/openapi-client.svg?branch=default-response-refs)](https://travis-ci.com/kiwiroy/openapi-client)

Resolve failing test in openapi-client

---

lib/Mojolicious/Plugin/OpenAPI.pm
lib/Mojolicious/Plugin/OpenAPI/SpecRenderer.pm
t/register.t

The type of object created for the default response, is created as a Schema object, not a response object.
Also clean out a few keys that does not belong in OpenAPI spec v3
Place the created default schema in the correct place as described in v3 specification, but also removal of few keys which does not belong there
* https://swagger.io/specification/#schema
* https://swagger.io/specification/#schemaObject
* https://swagger.io/specification/#responsesObject

this object belongs under components->schemas

---

t/register.t

This PR fixes a failing test due to changes in the recent JSON::Validator release
No more failing tests

Fix failing test due to recent JSON::Validator release

---

cpanfile
lib/JSON/Validator/OpenAPI/Mojolicious.pm
lib/Mojolicious/Plugin/OpenAPI/Guides/OpenAPI3.pod
t/register.t
t/spec/v3-invalid_file_refs.yaml
t/spec/v3-invalid_file_refs_no_path.yaml
t/spec/v3-invalid_include.yaml
t/spec/v3-valid_file_refs.yaml
t/spec/v3-valid_include.yaml
t/v3-invalid_file_refs.t
t/v3-invalid_file_refs_no_path.t
t/v3-valid_file_refs.t

in order to render proper OpenAPIv3 spec, overriding of generate_definitions_path() is needed
Latest changes to JSON::Validator makes it possible to render proper OpenAPIv3 specs for references
Reference to #138

Override generate_definitions_path()

---

lib/Mojolicious/Plugin/OpenAPI/Security.pm
t/plugin-security-extended-status.t

This one stashes a default 401 - unless there already is a status in the stash
A 500 will always be stashed.
With this approach the security callback can stash its own value (like 403) when user is authenticated but not authorized
In my case I do it like this:
```
if ($assume_client ne $apiuser and $account->{level} < 9999) {
$c->stash( status => 403 );
return 'permission denied' ;
};
```
Advantage over my other approach:
* fewer changes in the original module
* no new requirement for the parameter to $c->$cb

Another take on allowing different status codes

---

lib/JSON/Validator/OpenAPI/Mojolicious.pm
t/v3-body.t

According to the OpenAPI specification, requestBody can be optional so we need to follow that.
ref: https://github.com/jhthorsen/mojolicious-plugin-openapi/issues/170#issuecomment-671791298

support optional requestBody

---

lib/Mojolicious/Plugin/OpenAPI/Security.pm

The security plugin does not check for missing handlers correctly. The error handling code is never reached if there is only one handler in the spec and it is missing in the code.
This patch adds the necessary code path.

Update Security.pm to fix #254
